# Generated by Django 3.0 on 2020-04-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='home/logo/', verbose_name='Logo'),
        ),
    ]
